### PR TITLE
github: automate release creation

### PR DESCRIPTION
**Pull request by amorenoz**
Add release github action.
Basically copied it from [libovsdb](https://github.com/ovn-org/libovsdb/blob/main/.github/workflows/release.yml)'s :)

### CODE REVIEW

**Comment by amorenoz** [comment]
This generates awesome changelogs, see https://github.com/ovn-org/libovsdb/releases/tag/v0.6.0

**Comment by amorenoz** [comment]
What do you say @flavio-fernandes. Should we cut the first ovsdb-mon release?

**Comment by flavio-fernandes** [comment]
> What do you say @flavio-fernandes. Should we cut the first ovsdb-mon release?

yeah!!!

**Review by flavio-fernandes — COMMENTED** [review]
/lgtm

**Pull request merged**
